variables:
  REGISTRY: 'registry.gitlab.com/ebaneck/docker-ci_storelift'

image: gitlab/dind

services:
  - docker:dind
  
stages:
  - build-env
  - dev-env

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY  

build-env:
  stage: build-env
  script:
    - cd build-env
    - IMAGE_NAME='build-env'
    - docker build -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME $REGISTRY/$IMAGE_NAME
    - docker push $REGISTRY/$IMAGE_NAME
  only:
    - master

dev-env:
  stage: dev-env
  script:
    - cd dev-env
    - IMAGE_NAME='dev-env'
    - docker build -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME $REGISTRY/$IMAGE_NAME
    - docker push $REGISTRY/$IMAGE_NAME
  only:
    - master